{% set name = "nengo-loihi" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nengo-loihi-{{ version }}.tar.gz
  sha256: 4bbf60ba1d43592925385dfa61667863e7666c37802e354d629c718b5970c0c6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - jinja2
    - nengo >=3.1.0
    - packaging
    - python >=3.6
    - scipy
    - h5py
    - openpyxl
    - attrdict
    - numpy
    - pandas
    - matplotlib-base
    - imageio
    - scikit-image
    - scikit-learn
    - coloredlogs
    - protobuf
    - grpcio-tools
    - memory_profiler
    - bitstring

test:
  imports:
    - nengo_loihi
    - nengo_loihi.builder
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.nengo.ai/nengo-loihi
  summary: Run Nengo models on the Loihi chip
  license: LicenseRef-NENGO
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - Tobias-Fischer
